### ISSUE TITLE
THF branding

### ISSUE THREAD

**Issue by melisco** [HFAnalyticsLab/waiting-list-interactive#5]
Ensure app conforms with THF branding (new tasks to be added based on feedback from Comms team)
- [x] Colours
- [x] Fonts
- [x] Overall app layout

**Comment by melisco** [comment]
Have started adding colours in manually but may want to create a THF theme and/or change the dataframe created in the reactive to a long format and use colours within `aes()`?

**Comment by ChrisBeeley** [comment]
Package: https://github.com/THF-evaluative-analytics/THFstyle
